apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: Nodeport
  selector:
    app.kubenetes.io/app: synergychat-api
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 8080