apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  type: ClusterIP
  selector:
    app.kubenetes.io/app: synergychat-crawler
  ports:
    - port: 80
      targetPort: 8080