apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
  namespace: crawler
data:
  CRAWLER_PORT: "8080"
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"
  CRAWLER_KEYWORDS: "love,hate,joy,sadness,anger,disgust,fear,surprise"
  CRAWLER_DB_PATH: "/cache/db"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  namespace: crawler
  labels:
    app: synergychat-crawler
spec:
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-1
        envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        volumeMounts:
        - name: cache-volume
          mountPath: /cache

      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-2
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_2
        envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        volumeMounts:
        - name: cache-volume
          mountPath: /cache

      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler-3
        env:
          - name: CRAWLER_PORT
            valueFrom:
              configMapKeyRef:
                name: synergychat-crawler-configmap
                key: CRAWLER_PORT_3
        envFrom:
        - configMapRef:
            name: synergychat-crawler-configmap
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
      volumes:
      - name: cache-volume
        emptyDir:
---

apiVersion: v1
kind: Service
metadata:
  name: crawler-service
  namespace: crawler
spec:
  type: ClusterIP
  selector:
    app: synergychat-crawler
  ports:
    - port: 80
      targetPort: 8080