apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
data:
  CRAWLER_PORT: "8080"
  CRAWLER_KEYWORDS: "love,hate,joy,sadness,anger,disgust,fear,surprise"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: synergychat-crawler
  labels:
    app: synergychat-crawler
spec:
  selector:
    matchLabels:
      app: synergychat-crawler
  template:
    metadata:
      labels:
        app: synergychat-crawler
    spec:
      containers:
      - image: bootdotdev/synergychat-crawler:latest
        name: synergychat-crawler
        envFrom:
          - configMapRef:
              name: synergychat-crawler-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  type: ClusterIP
  selector:
    app: synergychat-crawler
  ports:
    - port: 80
      targetPort: 8080