apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-web-configmap
data:
  WEB_PORT: "8080"
  API_URL: "http://synchatapi.internal"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: synergychat-web
  name: synergychat-web
spec:
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
      - image: bootdotdev/synergychat-web:latest
        name: synergychat-webi
        envFrom:
          - configMapRef:
              name: synergychat-web-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: synergychat-web
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: synergychat-web
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50